# Generated by Django 5.1.6 on 2025-03-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='title',
        ),
    ]
